import { ProviderComponent } from "@/provider";
import "@/styles/global.scss";
import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import { cookies } from "next/headers";
import Image from "next/image";
import "react-quill/dist/quill.snow.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const inter = Be_Vietnam_Pro({
  subsets: ["vietnamese"],
  display: "swap",
  weight: "400",
});

const technical_logo = [
  {
    key: "next",
    image: "/static/logo/next-js.png",
  },
  {
    key: "nest",
    image: "/static/logo/nest-icon.png",
  },
  {
    key: "postgres",
    image: "/static/logo/postgres-icon.png",
  },
];

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;

  const locale = cookies().get("locale")?.value;
  const lang = locale && locale === "vi" ? "vi" : "en";

  return (
    <html lang={lang} className={inter.className}>
      <head>
        <script
          async
          src="https://cdn.socket.io/4.6.0/socket.io.min.js"
          integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <ProviderComponent>{children}</ProviderComponent>

        <section className="flex flex-col p-4  gap-4 bg-cyan-200 dark:bg-slate-600 bg-opacity-40">
          <div className="flex flex-row  gap-4 justify-center ">
            {technical_logo.map((icon) => {
              return (
                <Image
                  key={`home-${icon.key}-icon`}
                  src={icon.image}
                  className="hover:scale-110 transition-transform cursor-pointer"
                  width={30}
                  height={30}
                  style={{
                    objectFit: "cover",
                  }}
                  alt={`${icon.key} icon`}
                />
              );
            })}
          </div>

          <h3 className="text-center text-sm font-semibold text-slate-900 dark:text-slate-100">
            Copyright ©2023 by Nguyen Hoang Lam
          </h3>
        </section>

        <script
          defer
          src="https://cdn.jsdelivr.net/npm/@preline/preline@1.0.0/dist/hs-ui.bundle.min.js"
        />
        <script
          defer
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.js"
        />
      </body>
    </html>
  );
}
