import { ProviderComponent } from "@/provider";
import "@/styles/global.scss";
import "@mantine/tiptap/styles.css";
import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import { cookies } from "next/headers";
import "react-quill/dist/quill.snow.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const inter = Be_Vietnam_Pro({
  subsets: ["vietnamese"],
  display: "swap",
  weight: "400",
});

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;

  const locale = cookies().get("locale")?.value;
  const lang = locale && locale === "vi" ? "vi" : "en";

  return (
    <html lang={lang} className={inter.className}>
      <head>
        <script
          async
          src="https://cdn.socket.io/4.6.0/socket.io.min.js"
          integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <ProviderComponent>{children}</ProviderComponent>

        <script
          defer
          src="https://cdn.jsdelivr.net/npm/@preline/preline@1.0.0/dist/hs-ui.bundle.min.js"
        />
        <script
          defer
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.js"
        />
      </body>
    </html>
  );
}
